server:
  port: 8085
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never
    include-binding-errors: never

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate   # troque por Flyway assim que criar as migrations
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true     # coloque true quando criar V1__init.sql

management:
  endpoints.web.exposure.include: health,info

client:
  post:
    url: http://localhost:8082

logging:
  level:
    io.github.resilience4j: DEBUG
    root: INFO
    com.coderbank.customer: ERROR
  pattern:
    console: >
      {"ts":"%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}","level":"%p",
       "logger":"%c{1}","msg":"%m","thread":"%t"}%n

resilience4j.circuitbreaker:
    instances:
      transactionServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10 # Número de chamadas consideradas para o cálculo da taxa de falha
        minimumNumberOfCalls: 5 # Número mínimo de chamadas para avaliar o desempenho
        permittedNumberOfCallsInHalfOpenState: 2 # Número de chamadas permitidas no estado half-open
        waitDurationInOpenState: 50s # Duração que o circuito permanece aberto antes de tentar fechar
        failureRateThreshold: 50 # Limite da taxa de falha para abrir o circuito



resilience4j.retry:
    instances:
      transactionServiceRetry:
        maxAttempts: 2 # Número máximo de tentativas
        waitDuration: 50ms  # Tempo de espera entre as tentativas
#        retryExceptions:

